import type { Profile } from '@/types'

export const demoProfile: Profile = {
  identity: {
    fullName: 'Aya Koffi N’Guessan',
    headline: 'Analyste financière senior · Marchés & gestion d’actifs',
    location: 'Abidjan, Côte d’Ivoire',
    bio: 'Analyste financière spécialisée en modélisation et allocation de portefeuille. 8 ans à accompagner PME et institutionnels sur la BRVM et les marchés obligataires ouest-africains.',
    photo: null,
    availability: 'open',
  },
  positions: [
    {
      id: 'pos-cgf',
      role: 'Analyste financière senior',
      company: 'CGF Bourse',
      startDate: '2023-06',
      endDate: null,
      description: "Couverture actions et obligataire sur la BRVM pour une clientèle institutionnelle ouest-africaine.",
      highlights: [
        '18 émetteurs suivis sur la BRVM',
        'Rendement moyen des recommandations : +14 % sur 12 mois',
        '6 notes de recherche publiées par trimestre',
      ],
    },
    {
      id: 'pos-nsia',
      role: 'Analyste financière',
      company: 'NSIA Banque',
      startDate: '2021-02',
      endDate: '2023-05',
      description: "Analyse crédit et montage de dossiers de financement pour PME régionales.",
      highlights: [
        '32 dossiers de financement instruits',
        'Portefeuille suivi : 4,8 Md FCFA',
      ],
    },
    {
      id: 'pos-boad',
      role: 'Chargée d’études économiques',
      company: 'BOAD',
      startDate: '2019-09',
      endDate: '2021-01',
      description: "Études sectorielles et suivi macroéconomique pour la zone UEMOA.",
      highlights: [
        '9 études sectorielles co-rédigées',
      ],
    },
    {
      id: 'pos-atlantique',
      role: 'Analyste junior',
      company: 'Banque Atlantique',
      startDate: '2018-09',
      endDate: '2019-08',
      description: "Stage puis CDD au sein de la direction des marchés de capitaux.",
      highlights: [
        'Automatisation du reporting hebdomadaire',
      ],
    },
  ],
  holdings: [
    { id: 'hold-modelisation', label: 'Modélisation financière', category: 'Analyse', weight: 16, years: 8 },
    { id: 'hold-portefeuille', label: 'Analyse de portefeuille', category: 'Analyse', weight: 14, years: 7 },
    { id: 'hold-valorisation', label: 'Valorisation d’entreprise', category: 'Analyse', weight: 8, years: 6 },
    { id: 'hold-risque-credit', label: 'Analyse de risque de crédit', category: 'Analyse', weight: 4, years: 5 },
    { id: 'hold-excel', label: 'Excel avancé · VBA', category: 'Outils', weight: 10, years: 8 },
    { id: 'hold-bloomberg', label: 'Bloomberg Terminal', category: 'Outils', weight: 8, years: 5 },
    { id: 'hold-powerbi', label: 'Power BI', category: 'Outils', weight: 6, years: 4 },
    { id: 'hold-sql', label: 'SQL', category: 'Outils', weight: 4, years: 3 },
    { id: 'hold-obligataire', label: 'Marché obligataire BRVM', category: 'Marchés', weight: 8, years: 5 },
    { id: 'hold-actions', label: 'Actions ouest-africaines', category: 'Marchés', weight: 6, years: 6 },
    { id: 'hold-devises', label: 'Devises & zone UEMOA', category: 'Marchés', weight: 4, years: 4 },
    { id: 'hold-conformite', label: 'Conformité BCEAO / UEMOA', category: 'Réglementation', weight: 12, years: 5 },
  ],
  certificates: [
    {
      id: 'cert-esatic',
      title: 'Licence Finance',
      institution: 'ESATIC',
      year: '2018',
      credentialUrl: null,
      fileUrl: null,
    },
    {
      id: 'cert-fhb',
      title: 'Master Finance de marché',
      institution: 'Université Félix Houphouët-Boigny',
      year: '2020',
      credentialUrl: null,
      fileUrl: null,
    },
    {
      id: 'cert-cfa',
      title: 'CFA Level I',
      institution: 'CFA Institute',
      year: '2022',
      credentialUrl: 'https://www.cfainstitute.org/verify',
      fileUrl: null,
    },
    {
      id: 'cert-cfi',
      title: 'Financial Modeling Certificate',
      institution: 'Corporate Finance Institute',
      year: '2023',
      credentialUrl: 'https://corporatefinanceinstitute.com/verify',
      fileUrl: null,
    },
  ],
  tickers: [
    { id: 'tick-linkedin', platform: 'linkedin', handle: 'aya-koffi-nguessan', url: 'https://linkedin.com/in/aya-koffi-nguessan' },
    { id: 'tick-x', platform: 'x', handle: 'ayakoffing', url: 'https://x.com/ayakoffing' },
    { id: 'tick-website', platform: 'website', handle: 'ayakoffi.com', url: 'https://ayakoffi.com' },
    { id: 'tick-email', platform: 'email', handle: 'aya.nguessan@example.com', url: 'mailto:aya.nguessan@example.com' },
  ],
  theme: {
    preset: 'terminal',
    accent: '#E4A93C',
    motion: 'full',
  },
}
